#include "GameplayTags/UiGameplayTags.h"

UISCREENFRAMEWORK_API UE_DEFINE_GAMEPLAY_TAG(Tag_UiLayerGame, "UI.Layer.Game")
UISCREENFRAMEWORK_API UE_DEFINE_GAMEPLAY_TAG(Tag_UiLayerMenu, "UI.Layer.Menu")
UISCREENFRAMEWORK_API UE_DEFINE_GAMEPLAY_TAG(Tag_UiLayerModal, "UI.Layer.Modal")


UISCREENFRAMEWORK_API UE_DEFINE_GAMEPLAY_TAG(Tag_ScreenHud, "UI.Screen.Hud")
UISCREENFRAMEWORK_API UE_DEFINE_GAMEPLAY_TAG(Tag_ScreenInventory, "UI.Screen.Inventory")
UISCREENFRAMEWORK_API UE_DEFINE_GAMEPLAY_TAG(Tag_ScreenModal, "UI.Screen.Modal")
UISCREENFRAMEWORK_API UE_DEFINE_GAMEPLAY_TAG(Tag_ScreenSettings, "UI.Screen.Settings")

UISCREENFRAMEWORK_API UE_DEFINE_GAMEPLAY_TAG(Tag_TooltipTestOne, "UI.Tooltip.Tooltip1")

