// Copyright People Can Fly. All Rights Reserved."

#pragma once
#include "NativeGameplayTags.h"

UISCREENFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_UiLayerGame)
UISCREENFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_UiLayerMenu)
UISCREENFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_UiLayerModal)

